### ISSUE TITLE
能不能通过文字转成各种英雄的语音呢

### ISSUE THREAD

**Issue by aqpmzngldh** [qiye45/HonorofKingsData#2]

**Comment by qiye45** [comment]
可以的，试试vits2



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月6日(周一) 中午12:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiye45/HonorofKingsData] 能不能通过文字转成各种英雄的语音呢 (Issue #2)

**Comment by aqpmzngldh** [comment]
> 可以的，试试vits2
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月6日(周一) 中午12:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [qiye45/HonorofKingsData] 能不能通过文字转成各种英雄的语音呢 (Issue #2) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

vits2是什么

**Comment by aqpmzngldh** [comment]
> 可以的，试试vits2
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月6日(周一) 中午12:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [qiye45/HonorofKingsData] 能不能通过文字转成各种英雄的语音呢 (Issue #2) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

谢谢，我去看看
